services:
  db:
    image: postgres
    container_name: local-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - local-postgres:/var/lib/postgresql/data
volumes:
  local-postgres:
    driver: local