version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
