version: '3.8'
services:
  db-test:
    image: remat-postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - remat-db:/var/lib/postgresql/data
volumes:
  remat-db:
    driver: local