services:
  db:
    image: postgres
    container_name: rawaf-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - rawaf-db1:/var/lib/postgresql/data
volumes:
  rawaf-db1:
    driver: local