version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - rawaf-db:/var/lib/postgresql/data
volumes:
  remat-db:
    driver: local