services:
  db-test:
    image: postgis/postgis:14-3.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - spga-db:/var/lib/postgresql/data
volumes:
  spga-db:
    driver: local