version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


networks:
  host:
    name: host
    external: true