version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=sa
      - POSTGRES_USER=sa
      - POSTGRES_DB=keycloak
    ports:
      - '5432:5432'
#    volumes:
#      - keycloak_db:/var/lib/postgresql/data
#    networks:
#      - web
#  keycloak:
#    image: quay.io/keycloak/keycloak:19.0.3
#    environment:
#      - KC_DB=postgres
#      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
#      - KC_DB_USERNAME=sa
#      - KC_DB_PASSWORD=sa
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command:
#      - start-dev
#    #    networks:
#    #      backend:
#    #        aliases:
#    #          - "keycloak"
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    networks:
#      - web
#volumes:
#  keycloak_db:
#networks:
#  web: