version: '3.8'
services:
  db-test:
    image: mohammadalsharif/spga-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - spga-db1:/var/lib/postgresql/data
volumes:
  spga-db1:
    driver: local