version: "3.9"
services:
  rabbitMq:
    image: rabbitmq:3
#    container_name: rabbitMQ
    hostname: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: hggih;fv10
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - D:\projects\docker\volumes\rabbit\:/var/lib/rabbitmq/
    restart: unless-stopped
