CREATE ROLE spgaadminuser WITH LOGIN SUPERUSER CONNECTION LIMIT -1 PASSWORD 'Spgau123456#';

CREATE DATABASE spga WITH  OWNER = spgaadminuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE spga TO spgaadminuser;

GRANT ALL ON SCHEMA public TO spgaadminuser;
CREATE EXTENSION postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
