version: "3.9"
services:
  ibm-mq:
    image: ibmcom/mq
    container_name: ibm-mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ENABLE_METRICS: 'true'
    volumes:
      - D:\projects\docker\volumes\ibm-mq3\:/mnt/mqm
    ports:
      - "1414:1414"
      - "9443:9443"
    restart: unless-stopped
