services:
  postgres-db:
    image: postgres
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-dev:/var/lib/postgresql/data
volumes:
  postgres-dev:
    driver: local