version: "3.9"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Hggih;fv10
    volumes:
      - G:\projects\docker\vloumes\sql-server\:/var/opt/mssql/data
    ports:
      - 1433:1433
    restart: unless-stopped


