version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
      - "1111:8080"
      - "2222:5000"
      - "1234:1234"
    container_name: jenkins
    volumes:
      - D:\projects\docker\volumes\jenkins\:/var/jenkins_home


