version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "1234:1234"
    container_name: jenkins
    volumes:
      - G:\projects\docker\vloumes\jenkins1\:/var/jenkins_home

