version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
#    volumes:
#      - G:\projects\docker\vloumes\mysql\:/var/lib/mysql
